name: check PR

on:
  pull_request:
    branches:
      - main

jobs:
  # Checkstyle Job
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository  # Maven local repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Checkstyle
        run: |
          echo "Running Checkstyle"
          # Simulate Checkstyle results
          echo "Checkstyle: ✅ Passed" >> $GITHUB_ENV
        continue-on-error: true  # This ensures the check doesn't stop if Checkstyle fails

  # Dependency Check Job
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository  # Maven local repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Dependency Check (Security Scan)
        run: |
          echo "Running Dependency Check"
          # Simulate Dependency Check results
          echo "Dependency Check: ✅ Passed" >> $GITHUB_ENV
        continue-on-error: true  # This ensures the check doesn't stop if Dependency Check fails

  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository  # Maven local repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build project
        run: |
          echo "Building project"
          # Simulate Build results
          echo "Build: ✅ Passed" >> $GITHUB_ENV
        continue-on-error: true  # This ensures the check doesn't stop if Build fails

  # Unit Tests Job
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository  # Maven local repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run unit tests
        run: |
          echo "Running unit tests"
          # Simulate Unit Tests results
          echo "Unit Tests: ✅ Passed" >> $GITHUB_ENV
        continue-on-error: true  # This ensures the check doesn't stop if Unit Tests fail
